### ISSUE TITLE
Latest Gazebo ROS for Shadow Hand

### ISSUE THREAD

**Issue by nomadik** [shadow-robot/sr-ros-interface#153]
Hello!

Dear Developers of the Shadow company,

for which latest vesrion of Gazebo you provide the simulation model?

P.S. Maybe this is not correct place to address questions. Please let me know
where it is better to do it? I have another questions about using the indigo/devel or hydro/devel and about the "sr_tactile_gazebo" in sr_tactile_sensor package.

Thanks,
Zhanat, UPMC

**Comment by shadowmanos** [comment]
Hi Zhanat,

thanks for your inquiry! Questions related to Shadow software are better
addressed at software@shadowrobot.com.
Feel free to open an issue at Github to report a bug for example.
Regarding the simulation specifically the best option I have at the moment
would be to get the latest source code for indigo and build it.
Instructions at the end of the email. For running the actual hand I would
recommend the hydro version.
That's because on the one hand a recent update on gazebo broke our hand's
simulation in both hydro and gazebo and we fixed it only on the latest
source for indigo.
On the other hand the current version of indigo is beta and has minor bugs
when using the actual hand while the hydro version works fine.
These bugs are being worked on at the moment with high priority and we will
do a new binary release soon for indigo where both simulated and actual
hands work perfectly!
So since you seem to be interested at the moment in simulation indigo from
source is the option. We will let you know by email when the new indigo
binary release is out.
That is if we know your email which I can't find through github.

Mind you that our indigo version is tested with
Ubuntu 14.04 and gazebo 2.2
while our hydro version is tested with
Ubuntu 12.04 and gazebo 1.9
The gazebo versions are the OSRF ones and the version is fixed for each ROS
version

Instructions to build indigo version of our hand's software :

sudo apt-get update
sudo apt-get install ros-indigo-desktop-full ros-indigo-ros-control
ros-indigo-ros-controllers
sudo apt-get install binutils-dev ros-indigo-rqt-common-plugins
sudo apt-get install gazebo2 ros-indigo-gazebo-ros-pkgs
mkdir ~/shadowhand
mkdir ~/shadowhand/src
cd ~/shadowhand/src git clone
https://github.com/shadow-robot/ros_ethercat.git
cd ~/shadowhand/src/ros_ethercat
git checkout indigo-devel
cd ~/shadowhand/src
git clone https://github.com/shadow-robot/sr-ros-interface-ethercat.git
cd ~/shadowhand/src/sr-ros-
interface-ethercat
git checkout indigo-devel
cd ~/shadowhand/src
git clone https://github.com/shadow-robot/sr-ros-interface.git
cd ~/shadowhand/src/sr-ros-interface
git checkout indigo-devel
cd ~/shadowhand/src
git clone https://github.com/shadow-robot/sr-visualization.git
cd ~/shadowhand/src/sr-visualization
git checkout indigo-devel
cd ~/shadowhand/src
source /opt/ros/indigo/setup.bash
catkin_make -DCMAKE_BUILD_TYPE=Release
source ~/shadowhand/devel/setup.bash

Hope this helps!

Cheers
Manos Nikolaidis

Software Team
Shadow Robot Company. 251 Liverpool Road, London U.K. N1 1LX
Tel: +44 (0) 20 7700 2487 E: manos@shadowrobot.com

On 3 September 2014 16:56, nomadik notifications@github.com wrote:

> Hello!
> 
> Dear Developers of the Shadow company,
> 
> for which latest vesrion of Gazebo you provide the simulation model?
> 
> P.S. Maybe this is not correct place to address questions. Please let me
> know
> where it is better to do it? I have another questions about using the
> indigo/devel or hydro/devel and about the "sr_tactile_gazebo" in
> sr_tactile_sensor package.
> 
> Thanks,
> Zhanat, UPMC
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shadow-robot/sr-ros-interface/issues/153.

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK
Registered Number 3308007 (England & Wales)

RoNeX - Building Robots with ROS Made Easy 

## http://www.shadowrobot.com/products/ronex/
