### ISSUE TITLE
Implement and test JointCommandInterfaces

### ISSUE THREAD

**Issue by shadowmanos** [shadow-robot/sr-ros-interface#161]
link the JointCommandInterfaces in ros_ethercat_model with the controller command
shadow-robot/ros_ethercat#15

**Comment by guihomework** [comment]
With this new interface, if I understood well this code in a position controller, 

``` cpp
command_ = joint_state_->commanded_position_ + joint_state_2->commanded_position_;
```

you want to send commands through j1 and j2 now, not j0 anylonger ? 
I am also wondering why the speed of the j0's in velocity controllers would not be the sum of both requested speed of j1 and j2 ?

``` cpp
command_ = (joint_state_->commanded_velocity_ + joint_state_2->commanded_velocity_) / 2.0;
```

To get the correct j1 and j2 speed, the j0 does have to turn at the sum of the speed requests to distribute the speed among j1 and j2, doesn't it ?

**Comment by shadowmanos** [comment]
This interfaces are meant to be used by various other controllers or sensor drivers to provide position commands and I tried to keep them flexible. If another controller or a sensor's driver generates a commanded position for the (virtual) j0 this can be applied divided by 2 to j1 and j2 commands or (perhaps simpler) leave j2 to zero and apply the whole of it to j1. If separate position command are received for j1 and j2, because that's how the other controller or sensor driver happens to work, they will simply be added as they can't be controlled separately.

I also found the divide by 2 formula for velocities a little bit strange but such a formula was there already and I just kept it as it is.

**Comment by toliver** [comment]
Yes, the division by 2 is wrong. We haven't been using nor paying much attention to the velocity controller recently, and I think it needs thorough testing in order to be usable.

**Comment by guihomework** [comment]
I only wanted to be sure you decided to have now a dual input to the j0 controllers (through a joint state containing 2 joints commands) instead of the single float representing a j0 command. This changes the way all the external programs are going to send commands.

Looking at initial code, the velocity command was set to the current mean value of the velocities at start and if not initialized. It is not such a problem at init, although it is strange. In the normal operation, the command of j0's was directly passed to command, so no j1 and j2 velocities averaged there. Now in normal operation, the mean value of the two commands is passed to j0. This should be tested, I don't think we want such a behaviour.

The choice of j1 or j2 or none to zero in the command input is very important. In the case of the biotac, j2 to zero would make no sense but with current j0s it is still ok as one controls a combination of two joints. If the command definitely change to dual inputs, I would vote for j1 and j2 both containing commands although they cannot be controlled separately (so current code for position command is ok)

Finally, to the best I understood ros_control, the chaining of controllers did not seem possible. So a controller itself offering a PositionCommandInterface as input cannot receive PositionCommands from another controller's output. I wish this was possible. 

Anyway cleaning the interfaces makes it clearer what type of data a controller is awaiting.

**Comment by shadowmanos** [comment]
_"This changes the way all the external programs are going to send
commands."_

The position controller for ffj0 for e.g. still subscribes to a topic named
_/sh_ffj0_position_controller/command_ and this topic will be used by _external
programs_ as always. The code in this branch has been successfully tested
with the joint slider GUI for e.g. that publishes at such command topics.
If you have code of your own that uses the command topics it shouldn't have
to be modified.
The joint command interfaces are not meant for use by *external programs *but
from inside the control loop. And since j0 are virtual joints without joint
state the commanded positions will have to refer to j1 and j2.

I will get rid of the _/ 2.0_ from the velocity controllers as everyone
including me seems to want.

Regarding the notorious _chaining of controllers *that you wish was
possible, I'll get back to you this week once I check some details myself.
I'll just note for now that controllers do not offer
*PositionCommandInterfaces_ as input,
the _class_ _RosEthercat : public hardware_interface::RobotHW_ instance
does.

Cheers
Manos Nikolaidis

Software Team
Shadow Robot Company. 251 Liverpool Road, London U.K. N1 1LX
Tel: +44 (0) 20 7700 2487 E: manos@shadowrobot.com

On 15 September 2014 16:03, GuiHome notifications@github.com wrote:

> I only wanted to be sure you decided to have now a dual input to the j0
> controllers (through a joint state containing 2 joints commands) instead of
> the single float representing a j0 command. This changes the way all the
> external programs are going to send commands.
> 
> Looking at initial code, the velocity command was set to the current mean
> value of the velocities at start and if not initialized. It is not such a
> problem at init, although it is strange. In the normal operation, the
> command of j0's was directly passed to command, so no j1 and j2 velocities
> averaged there. Now in normal operation, the mean value of the two commands
> is passed to j0. This should be tested, I don't think we want such a
> behaviour.
> 
> The choice of j1 or j2 or none to zero in the command input is very
> important. In the case of the biotac, j2 to zero would make no sense but
> with current j0s it is still ok as one controls a combination of two
> joints. If the command definitely change to dual inputs, I would vote for
> j1 and j2 both containing commands although they cannot be controlled
> separately (so current code for position command is ok)
> 
> Finally, to the best I understood ros_control, the chaining of controllers
> did not seem possible. So a controller itself offering a
> PositionCommandInterface as input cannot receive PositionCommands from
> another controller's output. I wish this was possible.
> 
> Anyway cleaning the interfaces makes it clearer what type of data a
> controller is awaiting.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shadow-robot/sr-ros-interface/issues/161#issuecomment-55603425
> .

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK
Registered Number 3308007 (England & Wales)

RoNeX - Building Robots with ROS Made Easy 

## http://www.shadowrobot.com/products/ronex/

**Comment by guihomework** [comment]
OK, I missed the moved setCommandCB 

``` cpp
joint_state_->commanded_position_ = msg->data;
```

I now better understand your explanation about j1 and j2. The external j0 command goes to the registered command interface j1, leaving j2 not used. In the case of an interface update (from internal only) of both j1 and j2, the command will be correctly created. This makes sense.
Nothing will break this way. thanks.

However, I read again several implemenation of controllers in ros_control (diff drive controllers or trajectory controllers), and I think the PositionCommandInterface that you create as a PositionJointInterface is a non-standard way of using the interface as it is not a direct link to the hardware.
In a standard RobotHW, one can understand that it provides a PositionJointInterface (input) since some robots have position as inputs (imagine a robot with basic servos, they only receive a position, no velocity, no torque). To my mind a RobotHW is not a controller, it is an interface to the robot hardware.

I am not sure controllers were meant to provide hardware input interfaces like what is currently implemented. The hardware interface like PositionJointInterface were meant to output the data to the hardware.

in theory 
traj ->topic-> [trajcontroller] ->HWPosJointInterface -> [RobotHW] ----> Robot

from what you designed I would draw it like this for a trajectory controller sending position commands

traj ->topic->[trajcontroller] ->HWPosJointInterface ->  [RobotHW] ->HWPosJointInterface ->  [MixedPosVelcontroller] -> HWEffortJointInterface -> [RobotHW] ----> Robot

It seems to be a weird work-around to chain controllers indirectly by using the RobotHW and its position interface as an internal storage to pass it from one controller to the other.  It also depends in which order are controllers called for this to work. Does the controller manager still have a scheduler as before ?
