### ISSUE TITLE
Check how to generate SRDF for any hand-arm combination

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ros-interface#215]
Ideally we want to generate dynamically the SRDF (and some other files needed to run moveit) for any combination of shadow hand + arm.

@guihomework has done work on this. Check that to see if we can use it.

**Comment by guihomework** [comment]
@toliver I update this comment to clarify

The work on a generic srdf for the _HAND only_ is done at 95% and mainly waiting two things :
- srdfdom should release the python parser required for sr_moveit_hand_config (you might ask them to release it in indigo).
- biotac hand requires kdl IK (not coupling IK) and this fails to load due to groups containing chains and joints. If the other shadow software need the chain and the joints this will not work. New investigations will be done  on that soon. 

There is not yet a srdf generation for an _arm + hand_. Ideally one should simply load both files that define the arm and hand separately and add some groups containing both elements. 
Is this what you plan to do ? I would like to be involved in that development as I have done a lot on that already.

**Comment by guihomework** [comment]
I have pushed several time the srdfdom developes to release my new parser but they always forget me. When this is done I can rework on that.
